import { StandardTableView } from "std-widgets.slint";

export global TestData {
    in property <[TableColumn]> test-packet-columns;
    in property <[[StandardListViewItem]]> test-packets;
}

export global ImageStream {
    in property <image> image;
}

export component MainWindow inherits Window {
    HorizontalLayout {
        StandardTableView {
            columns: TestData.test-packet-columns;
            rows: TestData.test-packets;
        }

        Image {
            width: 50%;
            height: 50%;
            source: ImageStream.image;
        }
    }
}
