import {
    StandardTableView,
    ComboBox,
    LineEdit,
    Button,
} from "std-widgets.slint";

export global Sender {
    in-out property <int> led_pattern: 0;
    callback test-send-data() -> int;
}

export global TestData {
    in property <[TableColumn]> test-packet-columns;
    in property <[[StandardListViewItem]]> test-packets;
}


export global ImageStream {
    in property <image> image;
}

component SettingBox inherits VerticalLayout {
    in property <string> label;

    alignment: start;

    i-label := Text {
        text: root.label;
    }

    Rectangle {
        @children
    }
}

export component MainWindow inherits Window {
    MenuBar {
        Menu {
            title: @tr("File");
            MenuItem {
                title: @tr("New");
                activated => {
                    file-new();
                }
            }

            MenuItem {
                title: @tr("Open");
                activated => {
                    file-open();
                }
            }
        }

        Menu {
            title: @tr("About");
            MenuItem {
                title: @tr("Attributions");
                activated => {
                    show-attributions();
                }
            }
        }
    }

    callback file-new();
    callback file-open();
    callback show-attributions();

    VerticalLayout {
        HorizontalLayout {
            spacing: 10px;

            VerticalLayout {
                alignment: start;

                padding: 10px;
                spacing: 12px;

                SettingBox {
                    label: "Type";
                    ComboBox {
                        model: ["Option 1", "Option 2"];
                    }
                }

                SettingBox {
                    label: "Name";
                    LineEdit { }
                }

                SettingBox {
                    label: "Frame Size";

                    ComboBox {
                        model: ["QVGA", "VGA", "SVGA", "UXGA"];
                    }
                }

                SettingBox {
                    label: "JPEG Quality";
                    LineEdit { }
                }

                SettingBox {
                    label: "Brightness";
                    LineEdit { }
                }

                SettingBox {
                    label: "Contrast";
                    LineEdit { }
                }

                SettingBox {
                    label: "Saturation";
                    LineEdit { }
                }

                SettingBox {
                    label: "Sharpness";
                    LineEdit { }
                }
            }

            VerticalLayout {
                alignment: start;

                Rectangle {
                    Button {
                        property <int> value: 0;
                        text: "TEST WS SEND: " + value;

                        clicked => {
                            self.value = Sender.test-send-data() - 1;
                        };
                    }
                }

                Rectangle {
                    ComboBox {
                        model: [
                            "DISPLAY_PATTERN_CORNERS",
                            "DISPLAY_PATTERN_CENTERS",
                            "DISPLAY_PATTERN_ENCIRCLE",
                            "DISPLAY_PATTERN_SHRINK_ENCIRCLE",
                            "DISPLAY_PATTERN_SHRINK_SQUARE",
                        ];
                        current-index: 0;

                        changed current-index => {
                            Sender.led_pattern = self.current-index
                        }
                    }
                }
            }

            StandardTableView {
                columns: TestData.test-packet-columns;
                rows: TestData.test-packets;
            }

            i-stream-image := Image {
                width: 50%;
                source: ImageStream.image;
            }
        }
    }
}
