import {
    StandardTableView,
    ComboBox,
    LineEdit,
    Button,
    AboutSlint,
} from "std-widgets.slint";

export global Sender {
    in-out property <int> led_pattern: 0;
    callback send-led-pattern();
}

export global Helper {
    in-out property <[string]> display-patterns;
}

export global DisplayRadarData {
    in property <[TableColumn]> test-packet-columns;
    in property <[[StandardListViewItem]]> test-packets;
}

export global ImageStream {
    in property <image> image;
}

export global CameraSettings {
    in-out property <[string]> frame-sizes;

    in-out property <int> stream-type-index: 0;
    in-out property <int> jpeg-quality: 12;
    in-out property <float> brightness: 0;
    in-out property <float> contrast: 0;
    in-out property <float> saturation: 0;
    in-out property <float> sharpness: 0;
}

export component MainWindow inherits Window {

    about_dialog := PopupWindow {
        Rectangle {
            background: black;
            AboutSlint { }
        }
    }

    MenuBar {
        Menu {
            title: @tr("Attributions");

            MenuItem {
                title: @tr("View Attributions");

                activated => {
                    about_dialog.show();
                }
            }
        }
    }

    VerticalLayout {
        HorizontalLayout {
            spacing: 10px;

            VerticalLayout {
                alignment: start;

                Rectangle {
                    ComboBox {
                        model: Helper.display-patterns;
                        current-index: 0;

                        changed current-index => {
                            Sender.led_pattern = self.current-index;
                            Sender.send-led-pattern();
                        }
                    }
                }
            }

            StandardTableView {
                columns: DisplayRadarData.test-packet-columns;
                rows: DisplayRadarData.test-packets;
            }

            Rectangle {
                background: orange;

                i-stream-image := Image {
                    width: 50%;
                    source: ImageStream.image;
                }
            }
        }
    }
}
