[package]
    name    = "server"
    version = "1.0.0"
    edition = "2024"
    build   = "build.rs"

[dependencies]
    shared = { workspace = true }

    tokio             = { version = "1.52.1", features = ["full"] }
    tokio-tungstenite = "0.29.0"
    futures-util      = "0.3.32"
    reqwest           = { version = "0.13.3", features = ["json"] }
    axum              = { version = "0.8.9", features = ["ws"] }
    mime_guess        = "2.0.5"
    include_dir       = "0.7.4"
    webbrowser        = "1.2.1"

[build-dependencies]
    anyhow                   = "1.0.102"
    wasm-bindgen-cli-support = "0.2.120"
